language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-vmstats.gemspec
- gem install sensu-plugins-vmstats-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: ALZmspSEe3XiQBKLpuk3YlCiw8U9izPwvAhvdFOr0V5XkuuMIj7h0fRTnEX90LXPcinGDbmUQdMTt0b2QlSuzrV8xGeWBTT3KQnrRAUmWCinbLI/owKmmScLpmhNUIVEZrucpUmbdTMddzymQ3ZAAOXVI3taYf3U6PdEdvQJfbs=
  gem: sensu-plugins-vmstats
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rmv: 2.4.1
    repo: sensu-plugins/sensu-plugins-vmstats
